/**
 * Central icon module — Phosphor icons exposed under the names used
 * throughout the app. Swap the underlying library here only.
 */
export {
  Warning as AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellSlash as BellOff,
  BellRinging as BellRing,
  BookOpen,
  Buildings as Building2,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUp,
  Circle,
  ClipboardText as ClipboardList,
  Clock,
  Copy,
  DownloadSimple as Download,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileMagnifyingGlass as FileCheck2,
  FileText,
  FileX as FileWarning,
  Flag,
  Prohibit as FlagOff,
  Folder,
  FolderOpen,
  Gear as Settings,
  Globe,
  DotsSixVertical as GripVertical,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  Tray as Inbox,
  Key as KeyRound,
  SquaresFour as LayoutDashboard,
  Link as Link2,
  LinkedinLogo as Linkedin,
  ListChecks,
  CircleNotch as Loader2,
  LockSimple as Lock,
  SignOut as LogOut,
  DeviceMobile,
  UserCircle,
  EnvelopeSimple as Mail,
  List as Menu,
  Microphone as Mic,
  Minus,
  Moon,
  DotsThree as MoreHorizontal,
  Package,
  SidebarSimple as PanelLeft,
  PencilSimple as Pencil,
  Plus,
  Printer,
  ArrowsClockwise as RefreshCw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  ShareNetwork as Share2,
  ShieldCheck,
  Sparkle as Sparkles,
  Square,
  Sun,
  Trash as Trash2,
  ArrowCounterClockwise as Undo2,
  UploadSimple as Upload,
  X,
  XCircle,
} from "@phosphor-icons/react";
