/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsIdIndexRouteImport } from './routes/requests.$id.index'
import { Route as RequestsIdDetailsRouteImport } from './routes/requests.$id.details'
import { Route as RequestsIdDocumentsRouteImport } from './routes/requests.$id.documents'
import { Route as RequestsIdDossierRouteImport } from './routes/requests.$id.dossier'
import { Route as RequestsIdExtractionRouteImport } from './routes/requests.$id.extraction'
import { Route as RequestsIdReadinessRouteImport } from './routes/requests.$id.readiness'
import { Route as RequestsIdRepaymentRouteImport } from './routes/requests.$id.repayment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdIndexRoute = RequestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdDetailsRoute = RequestsIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdDocumentsRoute = RequestsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdDossierRoute = RequestsIdDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdExtractionRoute = RequestsIdExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdReadinessRoute = RequestsIdReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdRepaymentRoute = RequestsIdRepaymentRouteImport.update({
  id: '/repayment',
  path: '/repayment',
  getParentRoute: () => RequestsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider/$id': typeof ProviderIdRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/portal/': typeof PortalIndexRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/requests/$id/documents': typeof RequestsIdDocumentsRoute
  '/requests/$id/dossier': typeof RequestsIdDossierRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/readiness': typeof RequestsIdReadinessRoute
  '/requests/$id/repayment': typeof RequestsIdRepaymentRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider/$id': typeof ProviderIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/portal': typeof PortalIndexRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/requests/$id/documents': typeof RequestsIdDocumentsRoute
  '/requests/$id/dossier': typeof RequestsIdDossierRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/readiness': typeof RequestsIdReadinessRoute
  '/requests/$id/repayment': typeof RequestsIdRepaymentRoute
  '/requests/$id': typeof RequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider/$id': typeof ProviderIdRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/portal/': typeof PortalIndexRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/requests/$id/documents': typeof RequestsIdDocumentsRoute
  '/requests/$id/dossier': typeof RequestsIdDossierRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/readiness': typeof RequestsIdReadinessRoute
  '/requests/$id/repayment': typeof RequestsIdRepaymentRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/provider/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/portal/'
    | '/requests/$id/details'
    | '/requests/$id/documents'
    | '/requests/$id/dossier'
    | '/requests/$id/extraction'
    | '/requests/$id/readiness'
    | '/requests/$id/repayment'
    | '/requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/provider/$id'
    | '/requests/new'
    | '/portal'
    | '/requests/$id/details'
    | '/requests/$id/documents'
    | '/requests/$id/dossier'
    | '/requests/$id/extraction'
    | '/requests/$id/readiness'
    | '/requests/$id/repayment'
    | '/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/provider/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/portal/'
    | '/requests/$id/details'
    | '/requests/$id/documents'
    | '/requests/$id/dossier'
    | '/requests/$id/extraction'
    | '/requests/$id/readiness'
    | '/requests/$id/repayment'
    | '/requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProviderIdRoute: typeof ProviderIdRoute
  RequestsIdRoute: typeof RequestsIdRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/': {
      id: '/requests/$id/'
      path: '/'
      fullPath: '/requests/$id/'
      preLoaderRoute: typeof RequestsIdIndexRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/details': {
      id: '/requests/$id/details'
      path: '/details'
      fullPath: '/requests/$id/details'
      preLoaderRoute: typeof RequestsIdDetailsRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/documents': {
      id: '/requests/$id/documents'
      path: '/documents'
      fullPath: '/requests/$id/documents'
      preLoaderRoute: typeof RequestsIdDocumentsRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/dossier': {
      id: '/requests/$id/dossier'
      path: '/dossier'
      fullPath: '/requests/$id/dossier'
      preLoaderRoute: typeof RequestsIdDossierRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/extraction': {
      id: '/requests/$id/extraction'
      path: '/extraction'
      fullPath: '/requests/$id/extraction'
      preLoaderRoute: typeof RequestsIdExtractionRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/readiness': {
      id: '/requests/$id/readiness'
      path: '/readiness'
      fullPath: '/requests/$id/readiness'
      preLoaderRoute: typeof RequestsIdReadinessRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/repayment': {
      id: '/requests/$id/repayment'
      path: '/repayment'
      fullPath: '/requests/$id/repayment'
      preLoaderRoute: typeof RequestsIdRepaymentRouteImport
      parentRoute: typeof RequestsIdRoute
    }
  }
}

interface RequestsIdRouteChildren {
  RequestsIdDetailsRoute: typeof RequestsIdDetailsRoute
  RequestsIdDocumentsRoute: typeof RequestsIdDocumentsRoute
  RequestsIdDossierRoute: typeof RequestsIdDossierRoute
  RequestsIdExtractionRoute: typeof RequestsIdExtractionRoute
  RequestsIdReadinessRoute: typeof RequestsIdReadinessRoute
  RequestsIdRepaymentRoute: typeof RequestsIdRepaymentRoute
  RequestsIdIndexRoute: typeof RequestsIdIndexRoute
}

const RequestsIdRouteChildren: RequestsIdRouteChildren = {
  RequestsIdDetailsRoute: RequestsIdDetailsRoute,
  RequestsIdDocumentsRoute: RequestsIdDocumentsRoute,
  RequestsIdDossierRoute: RequestsIdDossierRoute,
  RequestsIdExtractionRoute: RequestsIdExtractionRoute,
  RequestsIdReadinessRoute: RequestsIdReadinessRoute,
  RequestsIdRepaymentRoute: RequestsIdRepaymentRoute,
  RequestsIdIndexRoute: RequestsIdIndexRoute,
}

const RequestsIdRouteWithChildren = RequestsIdRoute._addFileChildren(
  RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProviderIdRoute: ProviderIdRoute,
  RequestsIdRoute: RequestsIdRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
