/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AiNoticeRouteImport } from './routes/ai-notice'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HelpRouteImport } from './routes/help'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalShareIdRouteImport } from './routes/portal.$shareId'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as RequestsIdIndexRouteImport } from './routes/requests.$id.index'
import { Route as RequestsIdDetailsRouteImport } from './routes/requests.$id.details'
import { Route as RequestsIdDocumentsRouteImport } from './routes/requests.$id.documents'
import { Route as RequestsIdDossierRouteImport } from './routes/requests.$id.dossier'
import { Route as RequestsIdExtractionRouteImport } from './routes/requests.$id.extraction'
import { Route as RequestsIdPackRouteImport } from './routes/requests.$id.pack'
import { Route as RequestsIdReadinessRouteImport } from './routes/requests.$id.readiness'
import { Route as RequestsIdRepaymentRouteImport } from './routes/requests.$id.repayment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNoticeRoute = AiNoticeRouteImport.update({
  id: '/ai-notice',
  path: '/ai-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalShareIdRoute = PortalShareIdRouteImport.update({
  id: '/portal/$shareId',
  path: '/portal/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdIndexRoute = RequestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdDetailsRoute = RequestsIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdDocumentsRoute = RequestsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdDossierRoute = RequestsIdDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdExtractionRoute = RequestsIdExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdPackRoute = RequestsIdPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdReadinessRoute = RequestsIdReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdRepaymentRoute = RequestsIdRepaymentRouteImport.update({
  id: '/repayment',
  path: '/repayment',
  getParentRoute: () => RequestsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-notice': typeof AiNoticeRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/portal/$shareId': typeof PortalShareIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/documents/': typeof DocumentsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/requests/$id/documents': typeof RequestsIdDocumentsRoute
  '/requests/$id/dossier': typeof RequestsIdDossierRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/pack': typeof RequestsIdPackRoute
  '/requests/$id/readiness': typeof RequestsIdReadinessRoute
  '/requests/$id/repayment': typeof RequestsIdRepaymentRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-notice': typeof AiNoticeRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/portal/$shareId': typeof PortalShareIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/documents': typeof DocumentsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/portal': typeof PortalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/requests/$id/documents': typeof RequestsIdDocumentsRoute
  '/requests/$id/dossier': typeof RequestsIdDossierRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/pack': typeof RequestsIdPackRoute
  '/requests/$id/readiness': typeof RequestsIdReadinessRoute
  '/requests/$id/repayment': typeof RequestsIdRepaymentRoute
  '/requests/$id': typeof RequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-notice': typeof AiNoticeRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/portal/$shareId': typeof PortalShareIdRoute
  '/provider/$id': typeof ProviderIdRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/documents/': typeof DocumentsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/requests/$id/details': typeof RequestsIdDetailsRoute
  '/requests/$id/documents': typeof RequestsIdDocumentsRoute
  '/requests/$id/dossier': typeof RequestsIdDossierRoute
  '/requests/$id/extraction': typeof RequestsIdExtractionRoute
  '/requests/$id/pack': typeof RequestsIdPackRoute
  '/requests/$id/readiness': typeof RequestsIdReadinessRoute
  '/requests/$id/repayment': typeof RequestsIdRepaymentRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/ai-notice'
    | '/auth'
    | '/help'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/learn/$slug'
    | '/portal/$shareId'
    | '/provider/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/documents/'
    | '/learn/'
    | '/portal/'
    | '/.lovable/oauth/consent'
    | '/requests/$id/details'
    | '/requests/$id/documents'
    | '/requests/$id/dossier'
    | '/requests/$id/extraction'
    | '/requests/$id/pack'
    | '/requests/$id/readiness'
    | '/requests/$id/repayment'
    | '/requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/ai-notice'
    | '/auth'
    | '/help'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/learn/$slug'
    | '/portal/$shareId'
    | '/provider/$id'
    | '/requests/new'
    | '/documents'
    | '/learn'
    | '/portal'
    | '/.lovable/oauth/consent'
    | '/requests/$id/details'
    | '/requests/$id/documents'
    | '/requests/$id/dossier'
    | '/requests/$id/extraction'
    | '/requests/$id/pack'
    | '/requests/$id/readiness'
    | '/requests/$id/repayment'
    | '/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/ai-notice'
    | '/auth'
    | '/help'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/security'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/learn/$slug'
    | '/portal/$shareId'
    | '/provider/$id'
    | '/requests/$id'
    | '/requests/new'
    | '/documents/'
    | '/learn/'
    | '/portal/'
    | '/.lovable/oauth/consent'
    | '/requests/$id/details'
    | '/requests/$id/documents'
    | '/requests/$id/dossier'
    | '/requests/$id/extraction'
    | '/requests/$id/pack'
    | '/requests/$id/readiness'
    | '/requests/$id/repayment'
    | '/requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AiNoticeRoute: typeof AiNoticeRoute
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  LearnSlugRoute: typeof LearnSlugRoute
  PortalShareIdRoute: typeof PortalShareIdRoute
  ProviderIdRoute: typeof ProviderIdRoute
  RequestsIdRoute: typeof RequestsIdRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-notice': {
      id: '/ai-notice'
      path: '/ai-notice'
      fullPath: '/ai-notice'
      preLoaderRoute: typeof AiNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$shareId': {
      id: '/portal/$shareId'
      path: '/portal/$shareId'
      fullPath: '/portal/$shareId'
      preLoaderRoute: typeof PortalShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/': {
      id: '/requests/$id/'
      path: '/'
      fullPath: '/requests/$id/'
      preLoaderRoute: typeof RequestsIdIndexRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/details': {
      id: '/requests/$id/details'
      path: '/details'
      fullPath: '/requests/$id/details'
      preLoaderRoute: typeof RequestsIdDetailsRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/documents': {
      id: '/requests/$id/documents'
      path: '/documents'
      fullPath: '/requests/$id/documents'
      preLoaderRoute: typeof RequestsIdDocumentsRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/dossier': {
      id: '/requests/$id/dossier'
      path: '/dossier'
      fullPath: '/requests/$id/dossier'
      preLoaderRoute: typeof RequestsIdDossierRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/extraction': {
      id: '/requests/$id/extraction'
      path: '/extraction'
      fullPath: '/requests/$id/extraction'
      preLoaderRoute: typeof RequestsIdExtractionRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/pack': {
      id: '/requests/$id/pack'
      path: '/pack'
      fullPath: '/requests/$id/pack'
      preLoaderRoute: typeof RequestsIdPackRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/readiness': {
      id: '/requests/$id/readiness'
      path: '/readiness'
      fullPath: '/requests/$id/readiness'
      preLoaderRoute: typeof RequestsIdReadinessRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/repayment': {
      id: '/requests/$id/repayment'
      path: '/repayment'
      fullPath: '/requests/$id/repayment'
      preLoaderRoute: typeof RequestsIdRepaymentRouteImport
      parentRoute: typeof RequestsIdRoute
    }
  }
}

interface RequestsIdRouteChildren {
  RequestsIdDetailsRoute: typeof RequestsIdDetailsRoute
  RequestsIdDocumentsRoute: typeof RequestsIdDocumentsRoute
  RequestsIdDossierRoute: typeof RequestsIdDossierRoute
  RequestsIdExtractionRoute: typeof RequestsIdExtractionRoute
  RequestsIdPackRoute: typeof RequestsIdPackRoute
  RequestsIdReadinessRoute: typeof RequestsIdReadinessRoute
  RequestsIdRepaymentRoute: typeof RequestsIdRepaymentRoute
  RequestsIdIndexRoute: typeof RequestsIdIndexRoute
}

const RequestsIdRouteChildren: RequestsIdRouteChildren = {
  RequestsIdDetailsRoute: RequestsIdDetailsRoute,
  RequestsIdDocumentsRoute: RequestsIdDocumentsRoute,
  RequestsIdDossierRoute: RequestsIdDossierRoute,
  RequestsIdExtractionRoute: RequestsIdExtractionRoute,
  RequestsIdPackRoute: RequestsIdPackRoute,
  RequestsIdReadinessRoute: RequestsIdReadinessRoute,
  RequestsIdRepaymentRoute: RequestsIdRepaymentRoute,
  RequestsIdIndexRoute: RequestsIdIndexRoute,
}

const RequestsIdRouteWithChildren = RequestsIdRoute._addFileChildren(
  RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AiNoticeRoute: AiNoticeRoute,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  LearnSlugRoute: LearnSlugRoute,
  PortalShareIdRoute: PortalShareIdRoute,
  ProviderIdRoute: ProviderIdRoute,
  RequestsIdRoute: RequestsIdRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
