/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsIdIndexRouteImport } from './routes/requests.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdIndexRoute = RequestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/$id': typeof RequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/requests/$id' | '/requests/new' | '/requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/requests/new' | '/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  RequestsIdRoute: typeof RequestsIdRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/': {
      id: '/requests/$id/'
      path: '/'
      fullPath: '/requests/$id/'
      preLoaderRoute: typeof RequestsIdIndexRouteImport
      parentRoute: typeof RequestsIdRoute
    }
  }
}

interface RequestsIdRouteChildren {
  RequestsIdIndexRoute: typeof RequestsIdIndexRoute
}

const RequestsIdRouteChildren: RequestsIdRouteChildren = {
  RequestsIdIndexRoute: RequestsIdIndexRoute,
}

const RequestsIdRouteWithChildren = RequestsIdRoute._addFileChildren(
  RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RequestsIdRoute: RequestsIdRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
